# Generated by Django 4.2 on 2024-08-22 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Título del evento"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción del evento"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        verbose_name="Fecha y hora de inicio del evento"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        verbose_name="Fecha y hora de fin del eventoo"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="¿Es público?"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
