# Generated by Django 4.2 on 2024-08-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default="Sin grupo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact_list.group",
                verbose_name="Grupo",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("primary", "Orange"),
                    ("success", "Green"),
                    ("info", "LightBlue"),
                    ("warning", "Yelow"),
                    ("danger", "Red"),
                ],
                max_length=10,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="contacts",
            field=models.ManyToManyField(
                related_name="tags", to="contact_list.contact"
            ),
        ),
    ]
