# Generated by Django 4.2 on 2024-08-19 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact_list", "0002_alter_contact_group_alter_tag_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default="GENERAL",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact_list.group",
                verbose_name="Grupo",
            ),
        ),
    ]
