# Generated by Django 4.2 on 2024-08-20 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact_list", "0003_alter_contact_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contact_list.group",
                verbose_name="Grupo",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
        ),
    ]
